### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by mark522412** [jawikas/pixelverse-auto-battle#2]
When i start the bot getting error: battlescount
![Annotation 2024-07-06 154955](https://github.com/jawikas/pixelverse-auto-battle/assets/126713789/5a32cc50-5e48-4002-8fef-7cda5e38efb2)

**Comment by jawikas** [comment]
it's usually an error with your data in config.json or on a website that is down.

**Comment by andreadstz** [comment]
![Screenshot 2024-07-07 151107](https://github.com/jawikas/pixelverse-auto-battle/assets/157999886/b06e5b8c-ace8-4046-8d57-fa0c3e97c151)

same her sir. even i just take a new query

**Comment by jawikas** [comment]
![image](https://github.com/jawikas/pixelverse-auto-battle/assets/63976518/c23dbfc6-0614-4aa3-905b-95dd2f11c0b1)
or on a website that is down.

**Comment by mark522412** [comment]
Its fixed now thank you. closing the issue
